"""
Gmail API Router (Multi-User Version)

Endpoints:
- GET  /api/email/inbox  → Fetch recent emails (for current user)
- GET  /api/email/{id}   → Get email details
- POST /api/email/send   → Send an email
"""

from fastapi import APIRouter, HTTPException, Query, Depends
from pydantic import BaseModel
from typing import Optional, List, Tuple
import os
from email.utils import parseaddr
from sqlalchemy.orm import Session

from utils.google_auth import is_authenticated
from utils.google_gmail import get_inbox, get_message, send_email
from database.connection import get_db
from database.models import User
from middleware import get_current_user

router = APIRouter(prefix="/email", tags=["Email"])


def _build_llm_fallback_chain() -> List[Tuple[str, object]]:
    """Build a fallback chain that mirrors chatbot model ordering."""
    from config.settings import (
        llm,
        llm_gemini_25_flash,
        llm_gemini_25_lite,
        llm_openrouter,
        llm_openrouter_alt,
        llm_openrouter_alt2,
    )

    has_google = bool(os.getenv("GOOGLE_API_KEY"))
    has_openrouter = bool(os.getenv("OPENROUTER_API_KEY"))

    models: List[Tuple[str, object]] = [("groq-primary", llm)]
    if has_google:
        models.append(("gemini-2.5-flash-lite", llm_gemini_25_lite))
    if has_openrouter:
        models.append(("openrouter-nemotron-30b", llm_openrouter))
    if has_google:
        models.append(("gemini-2.5-flash", llm_gemini_25_flash))
    if has_openrouter:
        models.append(("openrouter-trinity-large", llm_openrouter_alt))
        models.append(("openrouter-solar-pro", llm_openrouter_alt2))

    return models


def _is_retryable_llm_error(error_text: str) -> bool:
    lowered = error_text.lower()
    return (
        "429" in lowered
        or "402" in lowered
        or "503" in lowered
        or "500" in lowered
        or "rate" in lowered
        or "overloaded" in lowered
        or "spend limit" in lowered
        or "balance" in lowered
    )


def _invoke_with_fallback(messages: List[tuple]) -> Tuple[str, str]:
    """Invoke available models in order until one returns a usable draft."""
    fallback_models = _build_llm_fallback_chain()
    if not fallback_models:
        raise HTTPException(status_code=502, detail="No AI model is configured for drafting replies.")

    last_error = ""
    for idx, (label, active_llm) in enumerate(fallback_models):
        try:
            response_msg = active_llm.invoke(messages)
            content = getattr(response_msg, "content", "")
            draft_text = str(content).strip()
            if not draft_text:
                raise Exception("Empty draft generated by model")
            return draft_text, label
        except Exception as exc:
            last_error = str(exc)
            if _is_retryable_llm_error(last_error) and idx < len(fallback_models) - 1:
                continue

    raise HTTPException(
        status_code=502,
        detail=f"Unable to generate AI reply draft right now. Last error: {last_error[:180]}"
    )


@router.get("/inbox")
def fetch_inbox(
    max_results: int = Query(50, description="Number of emails"),
    query: Optional[str] = Query("", description="Gmail search query"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Fetch recent inbox emails for the current user."""
    if not is_authenticated(current_user, db):
        raise HTTPException(status_code=401, detail="Google not connected. Please connect Google account in Settings.")
    
    try:
        emails = get_inbox(current_user, db, max_results=max_results, query=query)
        return {"status": "success", "emails": emails, "count": len(emails)}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/message/{message_id}")
@router.get("/{message_id}")
def fetch_email_detail(
    message_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Get full email details."""
    if not is_authenticated(current_user, db):
        raise HTTPException(status_code=401, detail="Google not connected. Please connect Google account in Settings.")
    
    try:
        message = get_message(current_user, db, message_id)
        return {"status": "success", "email": message}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


class SendEmailRequest(BaseModel):
    to: str
    subject: str
    body: str


@router.post("/send")
def send_new_email(
    to: str = Query(..., description="Recipient"),
    subject: str = Query(..., description="Subject"),
    body: str = Query(..., description="Body"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Send an email from the current user's Gmail account."""
    if not is_authenticated(current_user, db):
        raise HTTPException(status_code=401, detail="Google not connected. Please connect Google account in Settings.")
    
    try:
        result = send_email(current_user, db, to=to, subject=subject, body=body)
        return {"status": "success", "result": result}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/ai-reply-draft")
def generate_ai_reply_draft(
    message_id: str = Query(..., description="Message ID to draft a reply for"),
    tone: str = Query("professional", description="Reply tone: professional, friendly, formal, brief"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Generate an AI email reply draft from an existing Gmail message."""
    if not is_authenticated(current_user, db):
        raise HTTPException(status_code=401, detail="Google not connected. Please connect Google account in Settings.")

    try:
        message = get_message(current_user, db, message_id)

        sender_raw = message.get("from", "")
        sender_name, sender_email = parseaddr(sender_raw)
        reply_to = sender_email or sender_raw

        original_subject = (message.get("subject") or "").strip()
        if original_subject.lower().startswith("re:"):
            reply_subject = original_subject
        else:
            reply_subject = f"Re: {original_subject}" if original_subject else "Re:"

        source_text = ((message.get("body") or "").strip() or (message.get("snippet") or "").strip())
        if not source_text:
            raise HTTPException(status_code=400, detail="Email body is empty. Cannot generate a draft reply.")

        safe_tone = (tone or "professional").strip().lower()
        allowed_tones = {"professional", "friendly", "formal", "brief"}
        if safe_tone not in allowed_tones:
            safe_tone = "professional"

        system_prompt = (
            "You are an assistant that writes polished email replies. "
            "Return only the email body text, ready to send. "
            "Do not include markdown, subject lines, or explanatory notes."
        )

        user_prompt = f"""
Write a {safe_tone} email reply to the message below.

Sender Name: {sender_name or 'Unknown'}
Sender Address: {reply_to}
Original Subject: {original_subject or '(No Subject)'}

Original Message:
{source_text[:5000]}

Requirements:
- Keep it concise (about 4 to 8 sentences).
- Acknowledge the main point of the sender.
- Include a clear next step or confirmation.
- Keep the tone respectful and natural.
""".strip()

        draft_body, model_used = _invoke_with_fallback([
            ("system", system_prompt),
            ("human", user_prompt),
        ])

        return {
            "status": "success",
            "to": reply_to,
            "subject": reply_subject,
            "draft_body": draft_body,
            "model": model_used,
            "message_id": message_id,
        }

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
