import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import {
    ArrowRight,
    Bot,
    Calendar,
    CheckSquare,
    Mail,
    MapPin,
    MessageSquare,
    PlayCircle,
    AlertTriangle,
    RefreshCw,
    XCircle,
    CheckCircle2,
    Lock,
    Shield,
    type LucideIcon,
} from 'lucide-react';
import './LandingPage.css';

type Feature = {
    icon: LucideIcon;
    title: string;
    description: string;
    outcome: string;
};

type FaqItem = {
    question: string;
    answer: string;
};

const tools = [
    { name: 'Gmail', color: '#EA4335', bg: '#fff3e0' },
    { name: 'Calendar', color: '#1a73e8', bg: '#e3f2fd' },
    { name: 'Tasks', color: '#A142F4', bg: '#f3e5f5' },
    { name: 'Maps', color: '#FBBC04', bg: '#fff8e1' },
    { name: 'Sheets', color: '#0F9D58', bg: '#e8f5e9' },
    { name: 'Contacts', color: '#1a73e8', bg: '#e3f2fd' },
];

const features: Feature[] = [
    {
        icon: AlertTriangle,
        title: 'Detect meeting conflicts',
        description: 'Automatically scans your schedule and warns you about overlapping events and impossible back-to-backs before they happen.',
        outcome: 'Conflict-free scheduling',
    },
    {
        icon: Mail,
        title: 'Extract action items from Gmail',
        description: 'Triages your inbox to find requests and questions, converting them directly into prioritized tasks on your board.',
        outcome: 'Never drop the ball',
    },
    {
        icon: MapPin,
        title: 'Plan travel between locations',
        description: 'Reads physical meeting locations and adds intelligent transit or driving buffers directly to your calendar.',
        outcome: 'Always arrive on time',
    },
    {
        icon: Calendar,
        title: 'Generate optimized daily schedule',
        description: 'Takes your scattered tasks, meetings, and habits to build a realistic, conflict-free itinerary for the entire day.',
        outcome: 'Focus on execution',
    },
    {
        icon: MessageSquare,
        title: 'Explain why each task is prioritized',
        description: 'Ask the chatbot why it scheduled something. Agents explain their reasoning based on deadlines, context, and importance.',
        outcome: 'Transparent AI reasoning',
    },
    {
        icon: RefreshCw,
        title: 'Sync live Google data',
        description: 'Live two-way sync keeps G-ONE updated the second your Google Calendar or Gmail changes in the background.',
        outcome: 'Always up to date',
    },
];

const testimonials = [
    {
        initials: 'AS',
        name: 'Ananya Sharma',
        role: 'VP of Operations, Zeta Corp',
        bg: '#e3f2fd',
        color: '#1a73e8',
        quote: 'The multi-agent system caught a conflict between my flight and a board meeting that I had completely missed.',
    },
    {
        initials: 'RK',
        name: 'Rohan Krishnamurthy',
        role: 'Founder, Lumio Studio',
        bg: '#e8f5e9',
        color: '#0F9D58',
        quote: 'My favorite part is asking the chatbot to reorganize my afternoon. It talks to all the agents and outputs a perfect new plan.',
        featured: true,
    },
    {
        initials: 'PM',
        name: 'Priya Mehta',
        role: 'Head of Strategy, BuildFast',
        bg: '#f3e5f5',
        color: '#A142F4',
        quote: 'I used to spend an hour every morning planning my day. Now I just approve the plan generated by the AI pipeline.',
    },
];

const pricingPlans = [
    {
        name: 'Free',
        price: '0',
        period: 'forever free',
        button: 'Get started free',
        featured: false,
        features: ['Manual mode planner', '3 Google integrations', 'Basic task management', 'Standard AI models'],
    },
    {
        name: 'Pro',
        price: '19',
        period: 'per month, billed monthly',
        button: 'Start free 14-day trial',
        featured: true,
        features: ['Live mode auto-sync', 'Full multi-agent pipeline', 'Advanced conflict detection', 'Smart travel routing', 'Premium AI models'],
    },
    {
        name: 'Team',
        price: '49',
        period: 'per seat/month, billed annually',
        button: 'Contact sales',
        featured: false,
        features: ['Everything in Pro', 'Cross-team conflict resolution', 'Shared team dashboard', 'SSO & 2FA', 'Dedicated support'],
    },
];

const faqs: FaqItem[] = [
    {
        question: 'Is my Google data private and secure?',
        answer: 'Yes. G-ONE uses standard OAuth-based Google connections. Your password is never seen. Tokens are user-specific, stored securely, and protected by JWT authentication. You can disconnect your account at any time.',
    },
    {
        question: 'How does the multi-agent system work?',
        answer: 'When you request a plan, the Coordinator Agent breaks it down. The Calendar Agent reads events, the Task Agent checks deadlines, the Email Agent extracts actions, and the Travel Agent adds buffers. Finally, the Conflict Agent ensures everything fits before presenting the result.',
    },
    {
        question: 'What is the difference between Live Mode and Manual Mode?',
        answer: 'Live Mode continuously syncs with your Google account in the background. Manual Mode allows you to import data only when you explicitly click a button, giving you more control over API usage.',
    },
    {
        question: 'Does it work with non-Google tools?',
        answer: 'Currently, the agent architecture is heavily optimized for Google Workspace. Microsoft 365 and Notion support are planned for future versions.',
    },
];

function LogoMark({ small = false }: { small?: boolean }) {
    const size = small ? 14 : 16;
    return (
        <svg width={size} height={size} viewBox="0 0 16 16" fill="none" aria-hidden="true">
            <rect x="2" y="2" width="5" height="5" rx="1" fill="white" />
            <rect x="9" y="2" width="5" height="5" rx="1" fill="white" opacity=".6" />
            <rect x="2" y="9" width="5" height="5" rx="1" fill="white" opacity=".6" />
            <rect x="9" y="9" width="5" height="5" rx="1" fill="white" />
        </svg>
    );
}

function PlusIcon() {
    return (
        <svg width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
            <path d="M2 5h6M5 2v6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
        </svg>
    );
}

export function LandingPage() {
    const [openFaq, setOpenFaq] = useState(0);

    return (
        <div className="landing-pro">
            <nav>
                <Link to="/" className="nav-logo">
                    <div className="nav-logo-icon">
                        <LogoMark />
                    </div>
                    G-ONE
                </Link>
                <ul className="nav-links">
                    <li><a href="#features">Features</a></li>
                    <li><a href="#how">How it works</a></li>
                    <li><a href="#pricing">Pricing</a></li>
                    <li><a href="#faq">FAQ</a></li>
                </ul>
                <Link to="/login" className="nav-cta-ghost">Sign in</Link>
                <Link to="/register" className="nav-cta">Get started free</Link>
            </nav>

            <section className="hero-section">
                <div className="hero">
                    <div>
                        <div className="hero-badge"><span /> Multi-Agent Workspace Automation</div>
                        <h1>Save 2+ hours daily with your <em>AI-powered</em> Google Workspace</h1>
                        <p className="hero-sub">
                            G-ONE connects your Calendar, Gmail, Tasks, and Maps, then helps prioritize,
                            plan, and automate your day so you can focus on work that matters.
                        </p>
                        <div className="hero-actions">
                            <Link to="/register" className="btn-primary">
                                Start for free <ArrowRight size={14} />
                            </Link>
                            <a href="#how" className="btn-ghost">
                                <PlayCircle size={14} /> Watch demo
                            </a>
                        </div>
                        <div className="hero-stats">
                            <div className="hero-stat"><strong>12,000+</strong><span>Active users</span></div>
                            <div className="hero-stat-divider" />
                            <div className="hero-stat"><strong>2.4 hrs</strong><span>Avg time saved/day</span></div>
                            <div className="hero-stat-divider" />
                            <div className="hero-stat"><strong>4.9</strong><span>User rating</span></div>
                        </div>
                    </div>

                    <div className="hero-visual">
                        <div className="mockup-frame dashboard-mockup">
                            <div className="mockup-bar">
                                <div className="mockup-dot" style={{ background: '#ff5f57' }} />
                                <div className="mockup-dot" style={{ background: '#febc2e' }} />
                                <div className="mockup-dot" style={{ background: '#28c840' }} />
                                <div className="mockup-url">g-one.app/dashboard</div>
                            </div>
                            <div className="mockup-app-body">
                                <div className="mockup-sidebar">
                                    <div className="mockup-nav-item active"><Calendar size={14} /> Planner</div>
                                    <div className="mockup-nav-item"><Mail size={14} /> Inbox</div>
                                    <div className="mockup-nav-item"><CheckSquare size={14} /> Tasks</div>
                                </div>
                                <div className="mockup-main">
                                    <div className="mockup-header">
                                        <div className="mockup-title">Today&apos;s Optimized Plan</div>
                                        <div className="mockup-chip"><RefreshCw size={10} /> Live Mode</div>
                                    </div>

                                    <div className="mockup-stats-row">
                                        <div className="mockup-stat-box">
                                            <span>Focus Time</span>
                                            <strong>4h 30m</strong>
                                        </div>
                                        <div className="mockup-stat-box alert">
                                            <span>Conflicts</span>
                                            <strong>1 Resolved</strong>
                                        </div>
                                    </div>

                                    <div className="mockup-timeline">
                                        <div className="timeline-item meeting">
                                            <div className="time">10:00 AM</div>
                                            <div className="content">
                                                <strong>Design Sync</strong>
                                                <span>Zoom Room A</span>
                                            </div>
                                        </div>
                                        <div className="timeline-item travel">
                                            <div className="time">11:00 AM</div>
                                            <div className="content">
                                                <strong><MapPin size={10} style={{ display: 'inline', marginRight: 4 }} />Travel Buffer</strong>
                                                <span>Added by Travel Agent (25 mins)</span>
                                            </div>
                                        </div>
                                        <div className="timeline-item task active-task">
                                            <div className="time">11:30 AM</div>
                                            <div className="content">
                                                <strong>Review Q3 budget report</strong>
                                                <span>Extracted from Gmail</span>
                                            </div>
                                            <div className="ai-badge"><Bot size={10} /> High Priority</div>
                                        </div>
                                        <div className="timeline-item task">
                                            <div className="time">1:00 PM</div>
                                            <div className="content">
                                                <strong>Prepare board slides</strong>
                                                <span>Google Tasks</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section className="pipeline-section">
                <div className="section-center">
                    <h2 className="pipeline-heading">One request. <em>Multiple agents</em> working together.</h2>
                    <p className="pipeline-sub">Behind the scenes, specialized AI agents collaborate to organize your life.</p>
                </div>
                <div className="pipeline-visual">
                    <div className="pipeline-track">
                        <div className="pipeline-node"><Calendar size={20} /><span>Calendar</span></div>
                        <ArrowRight className="pipeline-arrow" />
                        <div className="pipeline-node"><CheckSquare size={20} /><span>Tasks</span></div>
                        <ArrowRight className="pipeline-arrow" />
                        <div className="pipeline-node"><Mail size={20} /><span>Email</span></div>
                        <ArrowRight className="pipeline-arrow" />
                        <div className="pipeline-node"><AlertTriangle size={20} /><span>Conflicts</span></div>
                        <ArrowRight className="pipeline-arrow" />
                        <div className="pipeline-node"><MapPin size={20} /><span>Travel</span></div>
                    </div>
                    <div className="pipeline-result">
                        <div className="result-box">
                            <Bot size={24} />
                            <strong>Optimized Plan</strong>
                        </div>
                    </div>
                </div>
            </section>

            <section className="problem-statement">
                <div className="section-center">
                    <div className="problem-grid">
                        <div className="problem-card old-way">
                            <div className="card-badge">The Old Way</div>
                            <ul className="problem-list">
                                <li><XCircle size={18} className="icon-red" /> Tasks are scattered across 4 different apps</li>
                                <li><XCircle size={18} className="icon-red" /> Meetings conflict constantly</li>
                                <li><XCircle size={18} className="icon-red" /> Emails hide critical action items</li>
                                <li><XCircle size={18} className="icon-red" /> Travel time is completely ignored</li>
                                <li><XCircle size={18} className="icon-red" /> You manually plan everything every morning</li>
                            </ul>
                        </div>
                        <div className="problem-card new-way">
                            <div className="card-badge">The G-ONE Way</div>
                            <ul className="problem-list">
                                <li><CheckCircle2 size={18} className="icon-green" /> Everything unified in one smart dashboard</li>
                                <li><CheckCircle2 size={18} className="icon-green" /> AI detects and resolves conflicts before they happen</li>
                                <li><CheckCircle2 size={18} className="icon-green" /> Action items extracted instantly from Gmail</li>
                                <li><CheckCircle2 size={18} className="icon-green" /> Commute times automatically added to your calendar</li>
                                <li><CheckCircle2 size={18} className="icon-green" /> Agents generate your perfect day in 2 seconds</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </section>

            <section className="integrations-section">
                <div className="section-center">
                    <h2 className="section-heading">Deep Google Workspace Integration</h2>
                    <p className="section-sub">Choose between <strong className="mode-badge live-mode">Live Mode</strong> for instant background syncing or <strong className="mode-badge manual-mode">Manual Mode</strong> for total control.</p>
                </div>
                <div className="integrations-grid">
                    {tools.map((tool) => (
                        <div className="integration-card" key={tool.name}>
                            <div className="integration-icon" style={{ background: tool.bg, color: tool.color }}>
                                <span style={{ width: 18, height: 18, borderRadius: 3, background: tool.color, display: 'block' }} />
                            </div>
                            <div className="integration-name">Google {tool.name}</div>
                            <div className="integration-status">Connected</div>
                        </div>
                    ))}
                </div>
                <div className="security-note">
                    <Shield size={16} />
                    <span><strong>Enterprise-grade security:</strong> OAuth-based connection, user-specific tokens, protected JWT authentication. You can disconnect anytime.</span>
                    <Lock size={16} />
                </div>
            </section>

            <section className="how" id="how">
                <div className="how-inner">
                    <div className="section-center">
                        <div className="section-tag">How it works</div>
                        <h2 className="section-heading">Up and running in 3 simple steps</h2>
                    </div>
                    <div className="steps">
                        <div className="step">
                            <div className="step-num">1</div>
                            <h4>Connect your Google account</h4>
                            <p>G-ONE securely fetches your Calendar, Gmail, Tasks, Maps, and Sheets using official OAuth.</p>
                        </div>
                        <div className="step">
                            <div className="step-num">2</div>
                            <h4>Set your preferences</h4>
                            <p>Tell G-ONE your working hours, default travel modes, and personal planning style.</p>
                        </div>
                        <div className="step">
                            <div className="step-num">3</div>
                            <h4>Let agents generate the plan</h4>
                            <p>A conflict-aware, fully optimized schedule is created instantly, balancing your meetings and tasks.</p>
                        </div>
                    </div>
                </div>
            </section>

            <section className="features" id="features">
                <div className="section-center">
                    <div className="section-tag">Backend Capabilities</div>
                    <h2 className="section-heading">Advanced AI architecture, simple UI</h2>
                </div>
                <div className="features-grid">
                    {features.map(({ icon: Icon, title, description, outcome }) => (
                        <div className="feat-card" key={title}>
                            <div className="feat-icon"><Icon size={18} strokeWidth={1.7} /></div>
                            <h3>{title}</h3>
                            <p>{description}</p>
                            <div className="feat-outcome">&#10003; {outcome}</div>
                        </div>
                    ))}
                </div>
            </section>

            <section className="testimonials">
                <div className="section-center">
                    <div className="section-tag">Customer stories</div>
                    <h2 className="section-heading">Loved by professionals who move fast</h2>
                    <p className="section-sub">From solo founders to busy teams, G-ONE gives hours back to people who need momentum.</p>
                </div>
                <div className="testi-grid">
                    {testimonials.map((item) => (
                        <div className="testi-card" key={item.name} style={item.featured ? { border: '1px solid var(--blue-mid)' } : undefined}>
                            <div className="testi-stars">
                                {Array.from({ length: 5 }).map((_, index) => <span className="star" key={index}>&#9733;</span>)}
                            </div>
                            <p className="testi-quote">&quot;{item.quote}&quot;</p>
                            <div className="testi-author">
                                <div className="testi-avatar" style={{ background: item.bg, color: item.color }}>{item.initials}</div>
                                <div>
                                    <div className="testi-name">{item.name}</div>
                                    <div className="testi-role">{item.role}</div>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </section>

            <section className="pricing" id="pricing">
                <div className="pricing-inner">
                    <div className="section-center">
                        <div className="section-tag">Pricing</div>
                        <h2 className="section-heading">Simple, transparent pricing</h2>
                        <p className="section-sub">Start free. Upgrade when you are ready. No hidden fees, no lock-in.</p>
                    </div>
                    <div className="pricing-grid">
                        {pricingPlans.map((plan) => (
                            <div className={`plan ${plan.featured ? 'featured' : ''}`} key={plan.name}>
                                {plan.featured && <div className="plan-badge">Most popular</div>}
                                <div className="plan-name">{plan.name}</div>
                                <div className="plan-price"><sup>$</sup>{plan.price}</div>
                                <div className="plan-period">{plan.period}</div>
                                <hr className="plan-divider" />
                                {plan.features.map((feature) => (
                                    <div className="plan-feature" key={feature}>
                                        <span className="plan-check">&#10003;</span>{feature}
                                    </div>
                                ))}
                                <Link to="/register" className={`plan-btn ${plan.featured ? 'plan-btn-solid' : 'plan-btn-outline'}`}>
                                    {plan.button}
                                </Link>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            <section className="faq" id="faq">
                <div className="section-center">
                    <div className="section-tag">FAQ</div>
                    <h2 className="section-heading">Common questions</h2>
                </div>
                <div className="faq-list">
                    {faqs.map((item, index) => (
                        <div className={`faq-item ${openFaq === index ? 'open' : ''}`} key={item.question}>
                            <button className="faq-q" type="button" onClick={() => setOpenFaq(openFaq === index ? -1 : index)}>
                                {item.question}
                                <span className="faq-icon"><PlusIcon /></span>
                            </button>
                            <div className="faq-a">
                                <p>{item.answer}</p>
                            </div>
                        </div>
                    ))}
                </div>
            </section>

            <footer>
                <div className="footer-inner">
                    <div className="footer-brand">
                        <Link to="/" className="footer-logo">
                            <div className="footer-logo-icon"><LogoMark small /></div>
                            G-ONE
                        </Link>
                        <p>The AI-powered planner that coordinates your entire Google Workspace.</p>
                        <div className="footer-social">
                            {/* Icons omitted for brevity */}
                            <a href="https://twitter.com" aria-label="Twitter"><div className="social-placeholder" /></a>
                            <a href="https://github.com" aria-label="GitHub"><div className="social-placeholder" /></a>
                            <a href="https://linkedin.com" aria-label="LinkedIn"><div className="social-placeholder" /></a>
                        </div>
                    </div>
                    <div className="footer-links">
                        <div className="footer-col">
                            <h4>Product</h4>
                            <a href="#features">Features</a>
                            <a href="#pricing">Pricing</a>
                            <Link to="/changelog">Changelog</Link>
                        </div>
                        <div className="footer-col">
                            <h4>Resources</h4>
                            <a href="#faq">Help Center</a>
                            <Link to="/blog">Blog</Link>
                            <Link to="/docs">API Docs</Link>
                        </div>
                        <div className="footer-col">
                            <h4>Legal</h4>
                            <Link to="/privacy">Privacy</Link>
                            <Link to="/terms">Terms</Link>
                        </div>
                    </div>
                </div>
                <div className="footer-bottom">
                    &copy; {new Date().getFullYear()} G-ONE. All rights reserved.
                </div>
            </footer>
        </div>
    );
}
