"""add_is_google_user

Revision ID: 1b64e09c7b9c
Revises: dffee05b13cc
Create Date: 2026-02-27 18:59:24.712727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b64e09c7b9c'
down_revision: Union[str, Sequence[str], None] = 'dffee05b13cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_google_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_google_user')
    # ### end Alembic commands ###
