"""add_preferences_json_to_user_settings

Revision ID: 82b245f5c4e6
Revises: 0ba75dd02e67
Create Date: 2026-03-12 23:19:28.790834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b245f5c4e6'
down_revision: Union[str, Sequence[str], None] = '0ba75dd02e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('preferences', sa.JSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'preferences')
    # ### end Alembic commands ###
