"""add_ai_persistence_tables

Revision ID: fdb1a2f6cfc4
Revises: f7af1857c046
Create Date: 2026-03-10 21:04:21.127628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdb1a2f6cfc4'
down_revision: Union[str, Sequence[str], None] = 'f7af1857c046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('optimized_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conflicts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('travel_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('productivity_score', sa.Integer(), nullable=True),
    sa.Column('overload_risk', sa.String(length=20), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('optimization_mode', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_plans_plan_date', 'ai_plans', ['plan_date'], unique=False)
    op.create_index('ix_ai_plans_user_id', 'ai_plans', ['user_id'], unique=False)
    op.create_table('google_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_google_tokens_user_id', 'google_tokens', ['user_id'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('attendees', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meetings_start_time', 'meetings', ['start_time'], unique=False)
    op.create_index('ix_meetings_user_id', 'meetings', ['user_id'], unique=False)
    op.create_table('productivity_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('meetings_count', sa.Integer(), nullable=True),
    sa.Column('travel_minutes', sa.Integer(), nullable=True),
    sa.Column('productivity_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_productivity_metrics_date', 'productivity_metrics', ['date'], unique=False)
    op.create_index('ix_productivity_metrics_user_id', 'productivity_metrics', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('work_start', sa.Time(), nullable=True),
    sa.Column('work_end', sa.Time(), nullable=True),
    sa.Column('productivity_mode', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_user_settings_user_id', 'user_settings', ['user_id'], unique=False)
    op.create_table('agent_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('log_level', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['ai_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_logs_agent_name', 'agent_logs', ['agent_name'], unique=False)
    op.create_index('ix_agent_logs_plan_id', 'agent_logs', ['plan_id'], unique=False)
    op.add_column('tasks', sa.Column('estimated_duration', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index('ix_tasks_due_date', 'tasks', ['due_date'], unique=False)
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.drop_column('users', 'google_token_expiry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'google_id')
    op.drop_index('ix_tasks_due_date', table_name='tasks')
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'source')
    op.drop_column('tasks', 'category')
    op.drop_column('tasks', 'estimated_duration')
    op.drop_index('ix_agent_logs_plan_id', table_name='agent_logs')
    op.drop_index('ix_agent_logs_agent_name', table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_index('ix_user_settings_user_id', table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index('ix_productivity_metrics_user_id', table_name='productivity_metrics')
    op.drop_index('ix_productivity_metrics_date', table_name='productivity_metrics')
    op.drop_table('productivity_metrics')
    op.drop_index('ix_meetings_user_id', table_name='meetings')
    op.drop_index('ix_meetings_start_time', table_name='meetings')
    op.drop_table('meetings')
    op.drop_index('ix_google_tokens_user_id', table_name='google_tokens')
    op.drop_table('google_tokens')
    op.drop_index('ix_ai_plans_user_id', table_name='ai_plans')
    op.drop_index('ix_ai_plans_plan_date', table_name='ai_plans')
    op.drop_table('ai_plans')
    # ### end Alembic commands ###
